### PR TITLE
LPS-33161 We don't create ddmField when we're translating a content and the field is set to be not localizable. Journal article XML also don't need to have that dynamic-content element

### PR DESCRIPTION
**Pull request by marcellustavares**

### CODE REVIEW

**Comment by marcellustavares** [comment]
Hi @jhinkey, @pablocp added a javadoc comment on 2df3ba18059fc5246967fb7e012d3f257953a428 but I removed on this pull request. Could you please review it and let me know if we can include the way it is?

Thanks

**Comment by jhinkey** [comment]
Hi @marcellustavares . If you would, please open an LRDOCS ticket. We're starting to request that as the process, as it's too easy to lose track of them in email. :-)

I'd like to have the Javadoc reviewed. @codyhoag is reviewing the Javadoc now. Thanks.

**Comment by jhinkey** [comment]
@marcellustavares, sending the Javadoc by itself in a pull request to @codyhoag is good.

Otherwise, if you're requesting we re-add ourselves and edit it, we'll need an LRDOCS ticket to keep track of things. Thanks.

**Comment by marcellustavares** [comment]
thanks @jhinkey, will send a pull request to @codyhoag after this commit gets in master.

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/17298. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
