### PR TITLE
LPS-41654 remove wrong role from nav-item??

### PR DESCRIPTION
**Pull request by juliocamarero**
Hey Eduardo, 

I think you created this taglib and you may know a reason for this, but I can't understand this aria role.... I tend to think it is wrong.... can you please review it?

thanks a lot!!

### CODE REVIEW

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/14943. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
I just checked and it may be left over from the old toolbar code. Thx.

**Comment by juliocamarero** [comment]
Yep, I think @csierra just moved it from one place to another... but thatcode was there from the old toolbar code, yup :)

**Comment by csierra** [comment]
yes... that's exactly what @csierra did :-)

**Comment by eduardolundgren** [comment]
Yep, I checked that and it was there. So I deleted the comment and add the new one. Thx!

**Pull request closed without merging**
