### PR TITLE
ddmschema

### PR DESCRIPTION
**Pull request by mhan810**

### CODE REVIEW

**Comment by mhan810** [comment]
just opened an lps: https://issues.liferay.com/browse/LPS-41253

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/14616

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/14646. [See changes here.](https://github.com/eduardolundgren/liferay-portal/compare/1353bd2~2...1353bd2) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
