### PR TITLE
LPS-35937

### PR DESCRIPTION
**Pull request by ipeychev**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
@ipeychev and @sergiogonzalez,

We have a notification implementation on AlloyUI queue, see https://github.com/eduardolundgren/alloy-ui/pull/98 the pull request.
Would be ideal if we use this code on the framework level instead of maintain a duplicated logic on Liferay.
On the review I will refactor to use alloy notifier module. This may take 1 day to be done.
Thank you.

**Comment by sergiogonzalez** [comment]
Hey Eduardo,

It seems good to me but we should prioritize this because it's part of an sponsored dev and this is the last thing we're missing. 

Sergio

**Comment by ipeychev** [comment]
Hey Eduardo,

It seems this PR is on your queue for 8 months? I wasn't aware it even existed. Why was it not merged for so long time?

**Comment by eduardolundgren** [comment]
It wasn't merged because we never needed it before :) The ideal would be use the widget from Alloy, although because it's a sponsored development I will go a head and merge until we get it done using the Alloy component.

Thank you guys! It was sent to Brian, https://github.com/brianchandotcom/liferay-portal/pull/11785.

**Pull request closed without merging**
