### PR TITLE
LPS-55749

### PR DESCRIPTION
**Pull request by samuelkong**
/cc @bejondshao

### CODE REVIEW

**Comment by samuelkong** [comment]
bump

**Comment by eduardolundgren** [comment]
Hey @samuelkong, can you fwd it to someone else? I won't be able to check that in the next couple of weeks. Thank you.

**Comment by samuelkong** [comment]
Hi @eduardolundgren, who do you recommend? Marcellus? Bruno Basto?

**Comment by eduardolundgren** [comment]
@marcellustavares

**Comment by samuelkong** [comment]
Thanks. PR sent to @marcellustavares https://github.com/marcellustavares/liferay-portal/pull/750

**Pull request closed without merging**
