### PR TITLE
LPS-47486 Safari only - SPA will continuously reload the page

### PR DESCRIPTION
**Pull request by marclundgren**
This has the same fix as AUI-1419.

### CODE REVIEW

**Comment by marclundgren** [comment]
`A.on('domready'` seems to have a bug. I need to see if there is another way I can fix it here.

**Comment by marclundgren** [comment]
`Liferay.on('domready...`

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/19606. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
