### PR TITLE
LPS-34453 paginate structure web content

### PR DESCRIPTION
**Pull request by marclundgren**
Hey @eduardolundgren here is my rebased branch. I even made some logic improvements. Here is my screen recording of usage: http://cl.ly/image/0O40153h3p04.

### CODE REVIEW

**Comment by eduardolundgren** [comment]
I am wondering if that will make into the release in time without causing issues. Maybe too late? I am going to leave it open until we decide. Thanks Marc. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by marclundgren** [comment]
kk if you need to call me anytime just hit me up. I can go on skype or
google hangout

On Thu, Sep 26, 2013 at 6:46 PM, Eduardo Lundgren
notifications@github.comwrote:

> Just started reviewing :)
> 
> [image: :octocat:]_Sent from GH http://nodegh.io._
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/eduardolundgren/liferay-portal/pull/432#issuecomment-25217217
> .

## 

Marc Lundgren

Software Engineer

Liferay, Inc. http://www.liferay.com

---

24-25 October 2012 |\* Liferay *_Spain Symposium_ |
liferay.com/spain2012http://www.liferay.com/spain2012

16 November 2012 |\* Liferay *_Italy Symposium_ |
liferay.com/italy2012http://www.liferay.com/italy2012

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request submitted to https://github.com/zenorocha/liferay-portal/pull/1. [See changes here.](https://github.com/eduardolundgren/liferay-portal/compare/dc20ff3fd855fd73a1d1fcd00409f522335c8d7d~0...dc20ff3fd855fd73a1d1fcd00409f522335c8d7d) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by marclundgren** [comment]
hi @eduardolundgren both your links are dead

https://github.com/zenorocha/liferay-portal/pull/1

https://github.com/eduardolundgren/liferay-portal/compare/dc20ff3fd855fd73a1d1fcd00409f522335c8d7d~0...dc20ff3fd855fd73a1d1fcd00409f522335c8d7d

**Comment by eduardolundgren** [comment]
Sorry. I was testing nodegh :)

**Pull request closed without merging**
