### PR TITLE
LPS-44457 Defaulting decorate and boundary params to null instead of true

### PR DESCRIPTION
**Pull request by robframpton**

### CODE REVIEW

**Comment by robframpton** [comment]
Hey @eduardolundgren 

I'm sending this to you because you reviewed and did some SF on the ticket that caused this issue (9448dd1fb44c13e9fcf5d3d318f6eae5e98c5bcc). The only real change that's being made is that we don't want to default the decorate value to true, because there is a fallback value in portlet.jsp already. Instead if either p_p_decorate or p_p_boundary is null, it passes null to the method that sets those attributes.

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
Pull request forwarded to https://github.com/marcellustavares/liferay-portal/pull/269. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by eduardolundgren** [comment]
I have forwarded to @marcellustavares since he participated on that. I tested here and seems that the minimize/restore is inconsistent with this fix. Try to minimize a portlet, refresh, you will see what I mean.

**Comment by robframpton** [comment]
I noticed an issue with the minimize/restore that existed in master without
my changes, did you try it on just master as well?

On Wed, Jun 18, 2014 at 12:13 PM, Eduardo Lundgren <notifications@github.com

**Comment by eduardolundgren** [comment]
I didn't try without your changes.
/cc @marcellustavares

**Pull request closed without merging**
