### PR TITLE
[TECHNICAL-SUPPORT] LPS-40988 LDAP - Make firstName and lastName attribute ignorable

### PR DESCRIPTION
**Pull request by NorbertKocsis**

### CODE REVIEW

**Comment by eduardolundgren** [comment]
@NorbertKocsis We should wait @marcellustavares for this one. I don't have any knowledge about the LDAP implementation we support right now. Is that possible due to our SLA?

**Comment by NorbertKocsis** [comment]
@eduardolundgren I don't think so. The ticket is already overdue, and I've been told Marcellus will be on vacation till the 20th.

**Comment by eduardolundgren** [comment]
@NorbertKocsis thank you

**Comment by shinnlok** [comment]
@NorbertKocsis 

This fix is fine. It was working/fixed before as shown in:

https://issues.liferay.com/browse/LPS-25484

and is a regression caused by:

https://github.com/liferay/liferay-portal/commit/9763e9865e2b52c7b63fb1e843b4860bba1fc5b1

Thanks!

**Comment by shinnlok** [comment]
To save some time/effort, I reviewed and forwarded the pull request to Brian:

https://github.com/brianchandotcom/liferay-portal/pull/14689

**Comment by eduardolundgren** [comment]
Thank you @shinnlok :)

**Pull request closed without merging**
